Change Account Name, Owner, Primary Contact
rackerlabs/docs-portal-onboarding-guide pull request #34
Opened 2022-09-01 16:37 UTC by Rohi2305

https://rackspace.atlassian.net/browse/DEXP-1589
https://rackspace.atlassian.net/browse/DEXP-1591
https://rackspace.atlassian.net/browse/DEXP-1592

2022-09-07 16:45 UTC, asmita32675 commented on docs/administrative/change_owner.rst
> +Change your Cloud Account Owner
Update the file name to match with title.

2022-09-07 16:45 UTC, asmita32675 commented on docs/administrative/change_account_name.md
> +---
Rename to .rst file.

2022-09-07 16:45 UTC, asmita32675 commented on docs/administrative/change_owner.rst
> +**Note: Only the current Acount Owner can assign a New Account Owner.**
```suggestion
**Note: Only the current Account Owner can assign a New Account Owner.**

- .. note::
```

2022-09-07 16:45 UTC, asmita32675 commented on docs/administrative/change_owner.rst
> +**Step 3** In Account Settings page, click **update** next to **Account Owner**.
```suggestion
**Step 3** In Account Settings page, click **update** next to **Account Owner**.
```
"Update"

2022-09-07 16:45 UTC, asmita32675 commented on docs/administrative/change_owner.rst
> +**Step 1** Log in to the `Rackspace Technology Customer Portal <https://login.rackspace.com>`_.
```suggestion
**Step 1** Log in to the `Rackspace Technology Customer Portal <https://login.rackspace.com>`_.

"Step #."
```

2022-09-07 16:45 UTC, asmita32675 commented on docs/administrative/change_owner.rst
> +**Step 5** Click **Confirm** to change the **Primary Account Owner**.
```suggestion
**Step 5** Click **Confirm** to change the **Primary Account Owner**.
```
change it to **Step 4**

2022-09-07 16:45 UTC, asmita32675 commented on docs/administrative/primary_contact.rst
> +**Note: The primary contact for your account must be an active user**
Use `- .. note::` to follow .rst format.

2022-09-07 16:45 UTC, asmita32675 commented on docs/administrative/primary_contact.rst
> +**Step 1.** Log in to the `Rackspace Technology Portal <https://login.rackspace.com/>.
Use  :ref: format like it was used on line 15 shown in red.

2022-09-07 16:45 UTC, asmita32675 commented on docs/administrative/primary_contact.rst
> +**Step 3.** Under **Compliance Documents and Forms** click **Primary Contact Change Form**. Complete the **Primary Contact Change Form** and attach it yo your support ticket.
```suggestion
**Step 3.** Under **Compliance Documents and Forms** click **Primary Contact Change Form**. Complete the **Primary Contact Change Form** and attach it on your support ticket. 
```

2022-09-12 13:12 UTC, Rohi2305 commented on docs/administrative/change_owner.rst
> +Change your Cloud Account Owner
updated

2022-09-12 13:12 UTC, Rohi2305 commented on docs/administrative/change_owner.rst
> +**Note: Only the current Acount Owner can assign a New Account Owner.**
Updated

2022-09-12 13:12 UTC, Rohi2305 commented on docs/administrative/change_owner.rst
> +**Step 1** Log in to the `Rackspace Technology Customer Portal <https://login.rackspace.com>`_.
Updated

2022-09-12 13:12 UTC, Rohi2305 commented on docs/administrative/change_owner.rst
> +**Step 5** Click **Confirm** to change the **Primary Account Owner**.
Updated

2022-09-12 13:14 UTC, Rohi2305 commented on docs/administrative/primary_contact.rst
> +**Step 3.** Under **Compliance Documents and Forms** click **Primary Contact Change Form**. Complete the **Primary Contact Change Form** and attach it yo your support ticket.
Updated

2022-09-12 16:34 UTC, Rohi2305 commented
Steven, please look for Change account name file and review my PRs.

2022-09-21 04:16 UTC, ssalinas24 requested changes

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/change_account_name.md
> +---
Some of the images like `Account Product & Severity...` and `Create Ticket.png` etc. are being added in this PR, but are they actually being used? I don't see them linked below. If they are no longer being used then can we remove them?

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/change_account_name.md
> +last_modified_date: '2022-07-04'
Update date to today or tomorrows date. To whenever you think we will have this merged.

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/change_account_name.md
> +<img width="331" alt="Create Ticket" src="Create Ticket.png">
update name. to all lower case, no spaces, and use dashes or (underscore if thats what other images have been doing in this repo) instead of spaces.

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/change_account_name.md
> +<img width="470" alt="Category" src="Category.png">
no caps on filenames

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/change_account_name.md
> +<img width="379" alt="Issue Details" src="Issue Details.png">
update file name as well

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/change_owner.rst
> +   :alt: accountsetting
alt tag should be regular text that people can read when hovering over the image or for screen reader to describe. Like make this a short fragment incomplete sentence with a few words that describe what is happening in the image.

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/change_owner.rst
> +   :alt: updateowner
update alt tag

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/change_owner.rst
> +   :alt: confirmnewowner
update alt tag

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/primary_contact.rst
> +   :alt: accdocs&forms
update alt tag

2022-09-21 04:16 UTC, ssalinas24 commented on docs/administrative/primary_contact.rst
> +   :alt: changeprimarycontactform
update alt tag

2022-10-19 13:52 UTC, asmita32675 requested changes

2022-10-19 13:52 UTC, asmita32675 commented on docs/administrative/update_primary_contact.rst
> +Update your account's primary contact
```suggestion
Update your Account's Primary Contact
```

2022-10-19 13:53 UTC, Rohi2305 commented on docs/administrative/update_primary_contact.rst
> +Update your account's primary contact
Done

2022-10-26 16:30 UTC, ssalinas24 commented on docs/administrative/change_cloud_account_owner.rst
> +**Step 3** In Account Settings page, click **update** next to **Account Owner**.
```suggestion
**Step 3** In Account Settings page, click **Update** next to **Account Owner**.
```

2022-10-26 16:44 UTC, ssalinas24 approved these changes

2022-10-26 17:06 UTC, merged